version: "3"

services:
  api:
    build:
      context: animals-api/.
    ports:
      - "8080:8080"
  app:
    build:
      context: animals-ui/.
    ports:
      - "2997:2997"
    depends_on:
      - "api"
    environment: 
      - API_URL=http://api:8080/api/1